apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app          # the Deployment's name
  labels:
    app: fastapi-app
spec:
  replicas: 3                # scale as necessary
  selector:
    matchLabels:
      app: fastapi-app       # <-- the Deployment finds its pods by THIS label
  template:                  # the pod blueprint
    metadata:
      labels:
        app: fastapi-app     # <-- pods stamped with this label; MUST match the selector above
    spec:
      containers:
        - name: fastapi
          image: fastapi-app:v4
          imagePullPolicy: IfNotPresent   # use the local image, don't try to pull from a registry
          ports:
            - containerPort: 8080
          env:
            - name: APP_VERSION
              value: "v1"
            - name: APP_GREETING
              valueFrom:
                configMapKeyRef:
                  name: fastapi-config
                  key: APP_GREETING
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: fastapi-secret
                  key: API_KEY
      securityContext:
        runAsNonRoot: true    # k8s REFUSES to start the pod if the image would run as root
        runAsUser: 1000       # run as UID 1000